;; OPTIONAL CONFIGURATIONS

(require 'init-secrets) 
(require 'init-org-setup) 
(require 'init-interface) 
(require 'init-interface-theme) 
(require 'init-os-specific) 
(require 'init-vc-backup) 
(require 'init-modeline) 
(require 'init-spelling) 
(require 'init-file-navigation) 
(require 'init-help-documentation) 
(require 'init-org-misc) 
(require 'init-org-agenda) 
(require 'init-org-todo) 
(require 'init-org-export) 
(require 'init-org-agenda-custom-view) 
(require 'init-org-capture) 
(require 'init-irc)
(require 'init-spotify) 
;;(require 'init-org-calendar)
;;(require 'init-org-calendar-calfw)
(require 'init-org-literate) 
(require 'init-rss) 
(require 'init-email) 
(require 'init-keybindings) 
;; (require 'init-evil)


(provide 'init-opt)
